heat_template_version: 2015-10-15
description: Builds a simple network topology and security group for use by generic grids.
parameters:
  external_network:
    type: string
    description: the external network for floating IP allocations
    default: public-138-net
  mgmt_cidr:
    type: string
    description: A management network will be created; this is the cidr to use on that network.
    default: 10.10.0.0/27
  container_cidr:
    type: string
    description: A container network will be created; this is the cidr to use on that network.
    default: 10.0.0.0/22
  protocol_cidr:
    type: string
    description: A protocol network will be created; this is the cidr to use on that network.
    default: 10.20.0.0/27
resources:
  mgmt_net:
    type: OS::Neutron::Net
    properties:
      name: mgmt-net

  mgmt_subnet:
    type: OS::Neutron::Subnet
    depends_on: mgmt_net
    properties:
      name: mgmt-subnet
      network: {get_resource: mgmt_net}
      cidr: {get_param: mgmt_cidr}
      dns_nameservers: [172.23.25.240]

  container_net:
    type: OS::Neutron::Net
    properties:
      name: container-net
      #port_security_enabled: false

  container_subnet:
    type: OS::Neutron::Subnet
    depends_on: container_net
    properties:
      name: container-subnet
      network: {get_resource: container_net}
      cidr: {get_param: container_cidr}
      enable_dhcp: false

  proto_net:
    type: OS::Neutron::Net
    properties:
      name: protocol-net

  proto_subnet:
    type: OS::Neutron::Subnet
    depends_on: proto_net
    properties:
      name: protocol-subnet
      network: {get_resource: proto_net}
      cidr: {get_param: protocol_cidr}
      enable_dhcp: false


  router:
    type: OS::Neutron::Router
    properties:
      name: ib-router
      external_gateway_info:
        network: { get_param: external_network }

  router_mgmt:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: router}
      subnet: {get_resource: mgmt_subnet}

  router_container:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: router}
      subnet: {get_resource: container_subnet}

  router_protocol:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: router}
      subnet: {get_resource: proto_subnet}

  sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: Infoblox
      description: This security group opens the ports needed by Infoblox DDI appliances.
# for now, just make it wide-open
      rules: [ {direction: egress}, {direction: ingress} ]
