heat_template_version: 2015-10-15
description: Launches a CoreOS cluster.
parameters:
  name:
    type: string
    description: the base host name for instances in the cluster
    default: host
  image:
    type: string
    description: The image to use (CoreOS, CoreOS_Beta, CoreOS_Alpha)
    default: CoreOS
    constraints:
      - custom_constraint: glance.image
  flavor:
    type: string
    description: Instance flavor for cluster members
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor
  security_group:
    type: string
    description: the security group to use
    default: DC/OS
  mgmt_network:
    type: string
    description: Management network for the cluster
    default: dcos-mgmt-net
  key_name:
    type: string
    description: Name of keypair to inject into the server.
    constraints:
      - custom_constraint: nova.keypair
  cluster_size:
    type: number
    description: the number of instances to launch
    default: 3
  discovery_token:
    type: string
    description: The cluster discovery token for discovery.etcd.io
resources:
  server:
    type: OS::Nova::Server
    properties:
      name: { list_join: [ '-', [ { get_param: name }, 'bootstrap' ] ] }
      flavor: m1.small
      image: {get_param: image}
      key_name: {get_param: key_name}
      security_groups: [ { get_param: security_group } ]
      networks: [ {network: { get_param: mgmt_network } } ]
  cluster:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: cluster_size }
      resource_def:
        type: coreos-two-nics.yaml
        properties:
          name: { list_join: [ '-', [ { get_param: name }, '%index%' ] ] }
          image: { get_param: image }
          flavor: { get_param: flavor }
          key_name: { get_param: key_name }
          discovery_token: { get_param: discovery_token }
          security_group: { get_param: security_group }
          mgmt_network: { get_param: mgmt_network }
